pipeline {
    agent { dockerfile { dir 'example' } }

    environment {
        AZURE_STORAGE_ACCOUNT = 'codevaletartifacts'
        AZURE_CONTAINER_NAME  = 'jenkins'
        AZURE_ACCESS_KEY      = credentials('azure-access-key')
    }

    stages {
        stage('Test') {
            steps {
                sh 'date > timestamp.txt'
                archiveArtifacts 'timestamp.txt'
            }
        }
    }
}
