pipeline {
    agent { dockerfile { dir 'example' } }

    stages {
        stage('Test') {
            steps {
                sh 'date > timestamp.txt'
                archiveArtifacts 'timestamp.txt'
            }
        }
    }
}
